### ISSUE TITLE
Spec tests are failing in main

### ISSUE THREAD

**Issue by chelnak** [puppetlabs/puppetlabs-stdlib#1254]
This is a ticket to track the following:

- [ ] Find out what broke spec tests in main
- [ ] Fix spec tests

**Comment by pmcmaw** [comment]
I can confirm this is no longer the case. 
I have seen spec tests passing overnight (10 hours ago with no failures)
Link with passing spec tests https://github.com/puppetlabs/puppetlabs-stdlib/actions/runs/3033830642

I hope this is ok to close, If you think I have done this in error please feel free to contact me or reopen.
