### ISSUE TITLE
Upgrading Puppetlabs-stdlib

### ISSUE THREAD

**Issue by bitvijays** [puppetlabs/puppetlabs-stdlib#1291]
Dear Puppetlabs Team,

Hope you are doing well and thank you for your continuous support making puppet better. It is always much appreciated.

## Describe the Bug
Trying to update `puppetlabs-stdlib`, update fails with 

```
Error: Could not upgrade module 'puppetlabs-stdlib' (v7.1.0 -> latest)
  Downgrading is not allowed.
```

## Expected Behavior
Should update to the latest version

## Steps to Reproduce

```
root@puppet:/etc/puppetlabs/code/environments/production/manifests# puppet module upgrade puppetlabs-stdlib
Notice: Preparing to upgrade 'puppetlabs-stdlib' ...
Notice: Found 'puppetlabs-stdlib' (v7.1.0) in /etc/puppetlabs/code/environments/production/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not upgrade module 'puppetlabs-stdlib' (v7.1.0 -> latest)
  Downgrading is not allowed.
```

## Environment

Puppet
```
puppet --version
6.25.1
```

```
uname -a
Linux puppet 4.19.0-21-cloud-amd64 #1 SMP Debian 4.19.249-2 (2022-06-30) x86_64 GNU/Linux
```

**Comment by alexjfisher** [comment]
Can you repeat with `--debug`?

**Comment by bitvijays** [comment]
Hi @alexjfisher , my apologies .. It's difficult to replicate now. I did updated with `--force` and unable to replicate now. We can close this issue probably.
