### ISSUE TITLE
validate_email_address doesn't recognize all valid emails

### ISSUE THREAD

**Issue by pier4r** [puppetlabs/puppetlabs-stdlib#1296]
## Describe the Bug
Some domains aren't recognized as valid by `validate_email_address`

## Expected Behavior
Every valid email should be recognized as such.

## Steps to Reproduce

Use `validate_email_address('test@this.is-a-domain.test')`

## Environment
 - Version: puppet 7.x
 - Platform: independent

## Additional Context
- A colleague discovered this.
- the problem is that a dash `-`sign is recognized in a subdomain, but not in the domain. Example 'test@this-works.domain.test' but 'test@this.does-not.test'
- Likely the [email Type in Stdlib](https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/types/email.pp), is better, would be possible to either use that in `validate_email_address` or deprecate the function as outdated, so that one looks elsewhere?

**Comment by b4ldr** [comment]
@pier4r thanks for the bug report however the validate_* set of functions are deprecated.  you should instead use tyope validation either on the class parameter e.g.

```puppet
class foobar (
  Stdlib::Email $email = 'test@this.does-not.test'
) { }
```
or as a comparison
```
if 'test@this.is-a-domain.test' =~ Stdlib::Email {
   # do stuff
} 
```
