### ISSUE TITLE
missing merge 1192

### ISSUE THREAD

**Issue by b4ldr** [puppetlabs/puppetlabs-stdlib#1297]
i just noticed that #1192 seems to be missing.  I don't see anything removing it and also don't see the commit in the [history](https://github.com/puppetlabs/puppetlabs-stdlib/commits/main/types).  Wondering if I'm missing something, if i need to submit again or if it was removed because of some other issues thanks

**Comment by alexjfisher** [comment]
Looks like you accidentally nuked it in https://github.com/puppetlabs/puppetlabs-stdlib/pull/1193 ?

Specifically, in https://github.com/puppetlabs/puppetlabs-stdlib/pull/1193/commits/6d0dbeb323021c22dc307537f79270dabbf51b24
