### ISSUE TITLE
Parser Functions using legacy facts

### ISSUE THREAD

**Issue by smoeding** [puppetlabs/puppetlabs-stdlib#1315]
## Describe the Bug
The two functions `has_interface_with` and `fqdn_rotate` do not work correctly when running the Puppet Agent with the `--no-include_legacy_facts` option that seems to be the default in Puppet 8. 

* `has_interface_with` uses `lookupvar(interfaces)` which is no longer available 
* `fqdn_rotate` calls `lookupvar(::fqdn)` which is also no longer available

## Expected Behavior
Both functions should work as before.

## Environment
 - Version 7.24.0 with option `--no_include_legacy_facts`
 - Platform Debian-11

**Comment by alexjfisher** [comment]
Half fixed in https://github.com/puppetlabs/puppetlabs-stdlib/pull/1326

**Comment by alexjfisher** [comment]
Remaining half of the issue fixed in #1341
