### ISSUE TITLE
RFC: Convert all Puppet 4.x API functions to namespaced variants

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/puppetlabs-stdlib#1346]
IMO, only core puppet functions should not have namespaces, and all stdlib functions should start `stdlib::`.

I'd like to suggest that all current 'modern' (non 3.x style) functions get converted to namespaced versions with a non-namespaced deprecated shim replacing the original file in the same way as is done [here](https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/lib/puppet/functions/has_interface_with.rb).

This was also the approach we took in `[extlib](https://github.com/voxpupuli/puppet-extlib/pull/120)` and `[postgresql](https://github.com/puppetlabs/puppetlabs-postgresql/commit/700d2c5bb54b7ea91d518de96e2c7a22318d0afa)`.

In a future major release we could drop the shims similar to how we did in `[extlib 5.0.0](https://github.com/voxpupuli/puppet-extlib/pull/153)`

**Comment by chelnak** [comment]
I think this is a reasonable suggestion.

Lets put it out to the wider community too (i'm sure many have already seen).. and get some votes.

**Comment by alexjfisher** [comment]
If this is the way we want to go, then perhaps either a rake task or some sort of helper (or both!) could reduce the tedious repetitiveness of creating the shims?? @ekohl - Any thoughts?

**Comment by ekohl** [comment]
I wonder if you need to declare them in the same filename as the function. Perhaps you could generate them in a for loop.

**Comment by alexjfisher** [comment]
Ooh, maybe that could work.  Or maybe you do if you want `puppet-strings` to mention them??

**Comment by alexjfisher** [comment]
Actually, I think a function can only be loaded if it's in the correct file.

**Comment by alexjfisher** [comment]
_and_ it has to have a call to `create_function` in it.

>The code loaded from modules/stdlib/lib/puppet/functions/foo.rb does not seem to be a Puppet 4x API function - no create_function call.

**Comment by smortex** [comment]
I am having a look at it ATM.  Some functions might not be namespaced, or more precisely they could be moved to Puppet itself.  I am thinking about:

* `fact()`
* `deprecation()`

Changing `fact(...)` to `stdlib::fact(...)` does not feel right (it is supposed to be some kind of shortcut and fail if we namespace it), and the `deprecation()` feature might also be available without stdlib.

Though?

**Comment by LukasAud** [comment]
Sounds reasonable to me to keep those three functions outside a namespace. Beauty often lies in simplicity. And depending on the cascading effect, namespacing them could result in a fairly large amount of small issues cascading into multiple other modules.

**Comment by smortex** [comment]
Great! The branch was rebased on top of main last week to fix conflicts. I just marked it as ready for review.
