### ISSUE TITLE
Calls to `Deprecation` function cause catalog compilation to fail if `strict` setting is set to `error`

### ISSUE THREAD

**Issue by alexjfisher** [puppetlabs/puppetlabs-stdlib#1373]
In stdlib 9.0 many functions were namespaced and non-namespaced deprecated shims were introduced to maintain compatibility with modules that haven't yet switched over to using the namespaced versions.

This largely works as intended, but (originally in #1365) it's been noted that the `deprecation` function will actually fail a catalog compile when [`strict` is set to `error`](https://github.com/puppetlabs/puppetlabs-stdlib/blob/44b6065d9e43e7b5d2983c91f6753627ceed550b/lib/puppet/functions/deprecation.rb#L32-L33), and that this is also the default in the upcoming Puppet 8.

This makes it very difficult for users to upgrade to stdlib 9 unless they're prepared to turn the `strict` setting back to `off` or `warning` (and there are many other good reasons for setting `strict` to `error`).  Since lots of modules are now also being updated to use the namespaced versions (requiring stdlib 9.0), upgrading a single affected component module now means having to upgrade _all_ modules that use stdlib functions.

Possible solutions include:
* Still leaving the shims documented as deprecated, but removing the calls to the `deprecation` function
* Adjusting deprecation so that it never raises an error

(This issue replaces #1365 where 2 separate issues were being discussed)

**Comment by robertc99** [comment]
One minor issue. Even if this is adjusted to produce warnings not errors, upgrading to stdlib9 will produce lots of ugly warnings from all the stdlib using modules which havent released a new version yet. Which could take a while.

One option would be to do a phased rollout.

For now,  document the functions as deprecated, but dont produce warnings.
In say 6 months, adjust so the functions produce deprecated warnings.
In a year,  adjust to follow the strict setting. People can still turn off strict, if they need to use some (hopefully unusual ) module that hasnt been updated.

**Comment by alexjfisher** [comment]
I think I'm ok with spamming warnings by default.  If they are causing you too much noise, there appear to already be two ways you could silence them.  You can use https://www.puppet.com/docs/puppet/7/configuration.html#disable-warnings to disable all deprecation warnings, or apparently also set the environment variable `STDLIB_LOG_DEPRECATIONS` to the `'false'` to disable just stdlib deprecation function generated warnings. (Looks like this [was designed](https://github.com/puppetlabs/puppetlabs-stdlib/commit/bec521e6b79dd612a73e742d1cb6371e17ade1a9) with being able to turn off warnings during testing, but I can't see why you couldn't also set this up on your puppetserver)

**Comment by bastelfreak** [comment]
My proposal from the Vox Pupuli meeting: Don't call deprecation, instead create a notify resource with warn as loglevel and maybe in addition warn() to log to the puppetserver as well.

**Comment by jhoblitt** [comment]
This is really ugly. As is, I doubt the community will ever upgrade to stdlib 9 because modules and their recursive deps which use stdlib function will need to switch to the namespaced version simultaneously. There absolutely needs to be a way to do incremental transition.  A few possibility are

* A new language construct to specifically handle converting from non-namespaced to namespaced functions one module at a time
* puppet 8 reverts the strict default back to warn
* stdlib removes the deprecation warning from the non-namespaced functions for the entire 9.x series
* a new 8.x release is made which includes namespaced versions of the functions but without the deprecation warnings

**Comment by jhoblitt** [comment]
My preference would be for 9.x to remove the deprecation warnings and plan to bring them back in 10.x.

/CC @smortex

**Comment by robertc99** [comment]
I have to agree. It would be best if there was a version where both the name spaced and non versions worked without warnings or errors, so people could upgrade as needed without issues.

**Comment by jhoblitt** [comment]
I am unfortunately having to pin `.fixture.yml` versions which had been intentionally left free floating as modules such as `puppetlabs/mysql` are updated to use stdlib 9.x namespace functions.  The more people start to pin versions of test fixtures due to stdlib 9.x namespaced functions the harder it is going to be for the everyone else in the community to upgrade.

**Comment by pmcmaw** [comment]
Hey everyone! Im just dropping a message to let you all know, we aren't ignoring you all and we are chatting in the background to come up with a reasonable change to resolve this for everyone. 👍

**Comment by bastelfreak** [comment]
a recommendation I posted on slack: cherry-pick the new namespaced functions into a 8.7 release. That would enable people to migrate to the name functions without a major version bump.

**Comment by chelnak** [comment]
> My proposal from the Vox Pupuli meeting: Don't call deprecation, instead create a notify resource with warn as loglevel and maybe in addition warn() to log to the puppetserver as well.

@bastelfreak I wonder if this may be the least impactful approach? We can then, as suggested above, re-add the deprecation function in a phased manner.

With regards to your post above. I'm a fan of moving forward. Maintaining a separate 8x could end up getting complicated.

**Comment by alexjfisher** [comment]
I think messing with the catalog to insert notify resources _might_ end up being overly complex and have subtle issues that are hard for us to fully anticipate.  For example, where are the new resources contained, and does this introduce dependency cycles for some people?

@chelnak What did you think about...

> I'm thinking add an extra optional parameter to deprecation that controls whether the strict puppet setting is used or not. Can default to true but be called with false in all the shims in at least this module.

I could code that up this morning for people to take a look.

**Comment by chelnak** [comment]
Good call actually. I hadn't considered that.

I'm happy with your suggestion 😄 .. I can help you get this pushed out too providing that the wider community are in agreement etc. Just let me know what you need.
