### ISSUE TITLE
fqdn_rotate function output often changes since v9

### ISSUE THREAD

**Issue by stevenpost** [puppetlabs/puppetlabs-stdlib#1381]
Commit e2d8b18c60b3f24e159fdae24b74f8d3224e06df broke the fqdn_rotate function as it no longer takes in only the fqdn as seed, instead it now takes in all the facts, which can change frequently.

There is already a PR open that would resolve this: https://github.com/puppetlabs/puppetlabs-stdlib/pull/1341
If this PR would take too long to merge, please consider reverting the mentioned commit.

**Comment by ic248** [comment]
Having the same issue and would be good to have this fixed
