### ISSUE TITLE
"is_email_address" deprecated function

### ISSUE THREAD

**Issue by sahaqaa** [puppetlabs/puppetlabs-stdlib#1416]
## Environment
- Puppet: 7.9.5
- Ruby: ruby 2.7.7p221 (2022-11-24 revision 168ec2b1e5) [x86_64-linux]
- Distribution: Ubuntu 20.04 LTS

## Additional Context
Please advice, in our code we use next block:
```
  unless is_email_address($admin_email) {
    fail('Invalid admin email address!')
  }
```
I can see that it was removed in v9.0.0 as "deprecated" function (https://github.com/puppetlabs/puppetlabs-stdlib/pull/1352/commits/f5c271082fd862301209a9f384caf811b4dd25c5)

In comments to that PR:
"This PR remove a bunch of legacy functions that are now part of Puppet or which where added to stdlib to allow parameters validation prior to Puppet 4 introduction of data types."

But when checking Puppet 8 documentation i cannot find anything that can replace this function:
https://www.puppet.com/docs/puppet/8/lang_functions.html
https://www.puppet.com/docs/puppet/8/function.html

In theory this function was useful and was doing it's job, to make sure that email that is passed is valid. And there seems to be no substitution for it as of now.

## Main reason why
We had an issue when every time we would execute "puppet agent -t" there would be applied "corrective" actions related to PPA.
We did search and saw that to get it fixed we need to update module "puppetlabs-apt".
and we decided to upgrade to latest version at that time:
mod 'puppetlabs-apt', '9.2.0'

But 'puppetlabs-apt', '9.2.0' depends on version puppetlabs-stdlib (>= 9.0.0 < 10.0.0).

So i would keep getting error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Unknown function: 'is_email_address'. (file: /etc/puppetlabs/code/environments/xxx/site/profile/manifests/reverseproxy.pp, line: 40, column: 10) on node grafana
```

For now we upgraded to mod 'puppetlabs-apt', '9.0.1' which is still supporting older version:
puppetlabs/stdlib (>= 4.16.0 < 9.0.0)

**Comment by ekohl** [comment]
There's a [Stdlib::Email](https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/types/email.pp) type (introduced ~3 years ago) that can be used. So the replacement is:
```puppet
unless $admin_email =~ Stdlib::Email {
  fail('Invalid admin email address!')
}
```

It's even better to use it as a type when it gets defined, for example in a class parameter.

**Comment by sahaqaa** [comment]
Thank you, will try to use it

**Comment by sahaqaa** [comment]
It worked good. Thank you :+1:
